### ISSUE TITLE
Problem with lan

### ISSUE THREAD

**Issue by Hoxeno** [blizzless/blizzless-diiis#138]
Me and a friend are trying to do a lan play, but when he start blizzless.exe he gets this error
[ Warn] [As]: Exception: - [Exception] System.Net.Sockets.SocketException (10049): Indirizzo richiesto non valido nel proprio contesto.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at DiIiS_NA.GameServer.ClientSystem.Base.AsyncAcceptor.Start(String ip, Int32 port) in D:\blizzless-diiis-test-stable\src\DiIiS-NA\D3-GameServer\ClientSystem\Base\AsyncAcceptor.cs:line 33
We set up hosts file and config file the same, with the ip of my machine (i host the server). What do we have to do?

**Comment by rgto** [comment]
Please try updating the server code with our latest branches, such as the test-stable and community branches, both of which are now up to date.
