### ISSUE TITLE
Ошибка при запуске Blizzless.exe

### ISSUE THREAD

**Issue by Zirae11** [blizzless/blizzless-diiis#157]
При запуске Blizzless выдает ошибку:
[08.06.2023 00:21:45.405] [Error] [BZ.Net]:    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DiIiS_NA.Program.Main() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Program.cs:line 212
[08.06.2023 00:21:45.410] [Fatal] [BZ.Net]: A root error of the server was detected, disconnection. - [Exception] System.AggregateException: One or more errors occurred. (An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

  * Database was not configured through Database method.
  * No mappings were configured through the Mappings method.
)
 ---> FluentNHibernate.Cfg.FluentConfigurationException: An invalid or incomplete configuration was used while creating a SessionFactory. Check PotentialReasons collection, and InnerException for more detail.

  * Database was not configured through Database method.
  * No mappings were configured through the Mappings method.

 ---> Npgsql.PostgresException (0x80004005): 28P01: ???????????? "postgres" ?? ?????? ???????? ??????????? (?? ??????)
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnector.AuthenticateMD5(String username, Byte[] salt, Boolean async)
   at Npgsql.NpgsqlConnector.Authenticate(String username, NpgsqlTimeout timeout, Boolean async)
   at Npgsql.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.ConnectorPool.AllocateLong(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<>c__DisplayClass32_0.<<Open>g__OpenLong|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Npgsql.NpgsqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection(String connectionString)
   at NHibernate.Connection.ConnectionProvider.GetConnection()
   at NHibernate.Tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.Prepare()
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.GetReservedWords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.UpdateDialectKeywords(Dialect dialect, IConnectionHelper connectionHelper)
   at NHibernate.Tool.hbm2ddl.SchemaMetadataUpdater.Update(ISessionFactoryImplementor sessionFactory)
   at NHibernate.Impl.SessionFactoryImpl..ctor(Configuration cfg, IMapping mapping, Settings settings, EventListeners listeners)
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
   --- End of inner exception stack trace ---
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
   at DiIiS_NA.Core.Storage.AccountDataBase.SessionProvider.CreateSessionFactory() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Core\Storage\AccountDataBase\SessionProvider.cs:line 75
   at DiIiS_NA.Core.Storage.AccountDataBase.SessionProvider.get_SessionFactory() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Core\Storage\AccountDataBase\SessionProvider.cs:line 35
   at DiIiS_NA.Core.Storage.DBSessions.SessionQuery[T]() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Core\Storage\DBSessions.cs:line 105
   at DiIiS_NA.Program.LoginServer() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Program.cs:line 128

  * Database was not configured through Database method.
  * No mappings were configured through the Mappings method.

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at DiIiS_NA.Program.Main() in D:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\Program.cs:line 212

**Comment by rgto** [comment]
Please try updating the server code with our latest branches, such as the test-stable and community branches, both of which are now up to date.
