### ISSUE TITLE
An error occurs when logging in.

### ISSUE THREAD

**Issue by Abab-bk** [blizzless/blizzless-diiis#166]
I successfully got into the game, then I logged out and back in and got an error when logging in.
log:
```
[10.08.2023 20:10:43.483] [Error] [BZ.Net]:    at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at DiIiS_NA.REST.JSON.Json.CreateObject[T](String jsonData, Boolean split) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\JSON\Json.cs:line 46
   at DiIiS_NA.REST.RestSession.HandleLoginRequest(HttpHeader request) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\RestSession.cs:line 133
   at DiIiS_NA.REST.RestSession.ReadHandler(Int32 transferredBytes) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\RestSession.cs:line 89
   at DiIiS_NA.REST.SocketBase.ReadHandlerInternal(SocketAsyncEventArgs args) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\SocketBase.cs:line 110
   at DiIiS_NA.REST.SocketBase.<AsyncRead>b__7_0(Object sender, SocketAsyncEventArgs args) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\SocketBase.cs:line 57
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
[10.08.2023 20:10:43.484] [Fatal] [BZ.Net]: A root error of the server was detected, disconnection. - [Exception] System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at DiIiS_NA.REST.JSON.Json.CreateObject[T](String jsonData, Boolean split) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\JSON\Json.cs:line 46
   at DiIiS_NA.REST.RestSession.HandleLoginRequest(HttpHeader request) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\RestSession.cs:line 133
   at DiIiS_NA.REST.RestSession.ReadHandler(Int32 transferredBytes) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\RestSession.cs:line 89
   at DiIiS_NA.REST.SocketBase.ReadHandlerInternal(SocketAsyncEventArgs args) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\SocketBase.cs:line 110
   at DiIiS_NA.REST.SocketBase.<AsyncRead>b__7_0(Object sender, SocketAsyncEventArgs args) in E:\Games\blizzless-diiis-test-stable\src\DiIiS-NA\REST\SocketBase.cs:line 57
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)
```

**Comment by iamdroppy** [comment]
Which branch are you on?

**Comment by Abab-bk** [comment]
test stable. It is work on my computer reboot.

**Comment by rgto** [comment]
Please try updating the server code with our latest branches, such as the test-stable and community branches, both of which are now up to date.
