### ISSUE TITLE
Unhandled DB exception caught - cannot get past game loading screen when joining world

### ISSUE THREAD

**Issue by Anix6** [blizzless/blizzless-diiis#171]
[09.10.2023 01:23:53.099] [ Warn] [DB]: Unhandled DB exception caught: - [Exception] System.ObjectDisposedException: Session is closed!
Object name: 'ISession'.
   at NHibernate.Impl.AbstractSessionImpl.ErrorIfClosed()
   at NHibernate.Impl.AbstractSessionImpl.CheckAndUpdateSessionStatus()
   at NHibernate.Impl.AbstractSessionImpl.ProcessHelper.BeginProcess(AbstractSessionImpl session)
   at NHibernate.Impl.StatelessSessionImpl.QueryOver[T]()
   at DiIiS_NA.Core.Storage.GameDBSession.SessionQueryWhere[T](Expression`1 predicate) in C:\Users\varad\Desktop\blizzless-diiis-test-stable\src\DiIiS-NA\Core\Storage\GameDBSession.cs:line 219

**Comment by breakingsword** [comment]
您好，我是周峰。您的邮件我已收到，我会尽快回复。

**Comment by rgto** [comment]
Please try updating the server code with our latest branches, such as the test-stable and community branches, both of which are now up to date.
