### ISSUE TITLE
System.Net.Sockets.SocketException (10013): 

### ISSUE THREAD

**Issue by wangshuai-wuhan** [blizzless/blizzless-diiis#189]
@dosu-bot
[06.09.2024 22:45:45.660] [ Info] [BZ.Net]: REST server started - 127.0.0.1:8081
[06.09.2024 22:45:45.681] [ Info] [BZ.Net]: Server BlizzLess.Net started - 127.0.0.1:8119
[06.09.2024 22:45:48.698] [ Info] [BZ.Net]: Starting Discord bot handler..
[06.09.2024 22:45:48.704] [ Warn] [As]: Exception: - [Exception] System.Net.Sockets.SocketException (10013): 以一种访问 权限不允许的方式做了一个访问套接字的尝试。
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at System.Net.Sockets.TcpListener.Start()
   at DiIiS_NA.GameServer.ClientSystem.Base.AsyncAcceptor.Start(String ip, Int32 port)
[06.09.2024 22:45:48.747] [Fatal] [S]: Listen failed to Start AsyncAcceptor on 127.0.0.1
[06.09.2024 22:45:49.154] [ Info] [BattleNetEmu]: Game server loaded 127.0.0.1:12877 connecting to BlizzLess.Net...

**Comment by mmmcatoo** [comment]
是不是使用了Windows，并且开启了Hyper-V如果是的话，需要用
`
netsh int ipv4 show excludedport tcp
`
查看是不是端口被系统排除给用户使用了，如果config.ini里面的端口有在排除列表里面的，我用的办法是给Hyper-V重新指定一个开启的端口范围。相关的命令是
`
netsh int ipv4 add excludedportrange protocol=tcp startport=1119 numberofports=1
`
重启电脑看看行不行了
@wangshuai-wuhan
