### ISSUE TITLE
Problem loading into a map.

### ISSUE THREAD

**Issue by Swoopy111** [blizzless/blizzless-diiis#37]
**So i followed a video tutorial, and everything worked fine until i wanted to load a map after i made my character.
I get this error in the server screen.**

[ Warn] [DB]: Unhandled DB exception caught: - [Exception] System.ObjectDisposedException: Session is closed!
Object name: 'ISession'.
   at NHibernate.Impl.AbstractSessionImpl.ErrorIfClosed()
   at NHibernate.Impl.AbstractSessionImpl.CheckAndUpdateSessionStatus()
   at NHibernate.Impl.AbstractSessionImpl.ProcessHelper.BeginProcess(AbstractSessionImpl session)
   at NHibernate.Impl.StatelessSessionImpl.QueryOver[T]()
   at DiIiS_NA.Core.Storage.GameDBSession.SessionQueryWhere[T](Expression`1 predicate) in C:\Users\Zxynorevanda5213515\Downloads\blizzless-diiis-b11s4\blizzless-diiis-b11s4\src\DiIiS-NA\Core\Storage\GameDBSession.cs:line 219

**I get this every time and i can't play the game at all just load it up and create a character.**

This is a screenshot of the server window.
https://i.imgur.com/tgqQj0z.png

**Comment by advocaite** [comment]
this is due to updating client
running via visual studio with a breakpoint this message goes away) but then the new player message crashes client
proberly some new op codes need sorting out
